In [2]:
import numpy as np

In [9]:
data=np.array([1,2,3,4,5,6])

In [10]:
print(data.ndim)
print(data.shape)
print(data.size)
print(data.dtype)
print(data.itemsize)
print(data.data)   #生成指向数组首地址的一个memoryview对象

1
(6,)
6
int32
4


In [11]:
data.shape=(3,2)
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
data.shape=(1,-1)
data

array([[1, 2, 3, 4, 5, 6]])

# 使用flatten()，ravel()会返回的数组会操作到原数组

In [18]:
print(data.ravel())   #数组横向展平
print(data.flatten()) #数组纵向展平

[1 2 3 4 5 6]
[1 2 3 4 5 6]


# 数组的组合，hstack()水平组合，vstack()垂直组合

In [22]:
a=np.array(([1],[2],[3]))
b=np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# hsplit()按照横向分割数组，vsplit()按照纵向分割数据，split()可以指定分割轴向，dsplit()要求数组的维度是3及以上

In [24]:
a=np.arange(16).reshape(4,4)
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [26]:
np.split(a,[2,3],axis=0)         #按照纵向分割，分隔位置第2行、第3行

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

# 自动生成数组

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(1,13,2)

array([ 1,  3,  5,  7,  9, 11])

In [29]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
np.linspace(1,10,10,endpoint=False)    #endpoint参数指定是否包含终值，默认值为True

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [31]:
np.logspace(0,3,4)         #与linspace类似，开始，结束，元素个数，默认底数为10

array([   1.,   10.,  100., 1000.])

In [32]:
np.logspace(0,3,4,base=2)      #可以通过指定base参数来确定底数

array([1., 2., 4., 8.])

# zeros()，ones()，empty()可以创建指定形状和类型的数组，其中empty()只分配数组所使用的内存，当并不对数组元素进行初始化操作

In [37]:
print(np.random.random())  #生成[0，1）之间指定数目的随机数组成的一维数组   

0.4476166507066527


In [43]:
print(np.random.rand())  #生成服从均匀分布的样本值

0.6969261453618366


In [44]:
print(np.random.randn())  #生成服从正态分布的样本值

0.6372492494283162


In [47]:
print(np.random.randint(1,10))  #生成指定上下限范围的随机数

2


In [83]:
np.random.randint(1,10,(3,3))

array([[7, 4, 6],
       [8, 6, 8],
       [7, 8, 8]])

In [50]:
np.random.seed()      #确定随机数生成器的种子 

In [54]:
a=np.array([1,2,3,4])
np.random.permutation(a)     #对一个序列进行随机排序，不改变原数组

array([2, 1, 4, 3])

In [55]:
np.random.shuffle(a)    #对一个序列进行随机排序，改变原数组  

In [66]:
np.sum(np.random.binomial(n=2,p=0.5,size=100000)==2)/100000      #产生二项分布的随机数，两枚硬币都是正门，实验100000次，概率接近0.25

0.24974

# 和列表不同的是，通过切片获取的新的数组是原始数组的一个视图，它与原始数组共享同一块数据存储空间，这就意味着在视图上的操作都会使得原始数组发生改变，如果需要的并非视图而是要复制数据，则可以通过copy()方法来实现，这时新旧两个数组不共享同一块数据存储空间

# 注意：使用列表作为下标得到的数组不和原始数组共享数据

# 创建矩阵：使用mat()函数 ,使用matrix()函数

In [78]:
print(np.mat(a).T)    #返回矩阵的转置

[[4]
 [3]
 [1]
 [2]]


In [80]:
print(np.mat(a).H)    #返回矩阵的共轭转置

[[4]
 [3]
 [1]
 [2]]


In [81]:
print(np.mat(a).I)   #返回逆矩阵

[[0.13333333]
 [0.1       ]
 [0.03333333]
 [0.06666667]]


In [82]:
print(np.mat(a).A)      #返回矩阵的视图

[[4 3 1 2]]


# 基本数组统计方法

In [93]:
a

array([4, 3, 1, 2, 1])

In [117]:
print('求和:',a.sum())
print('算术平均值:',a.mean())
print('标准差:',a.std())
print('方差:',a.var())
print('最小值最大值:',a.min(),a.max())
print('最小值和最大值的索引:',a.argmin(),a.argmax())
print('所有元素的累计和与累计积:',a.cumsum(),a.cumprod())
print('找出数组中的唯一值并返回已排序的结果:',np.unique(a))
print('把一个数组重复若干次:',np.tile(a,2))   #重复两次
print('按照轴向重复一个数组若干次:',np.repeat(a,2,axis=0))
print('排序:',np.sort(a))

求和: 11
算术平均值: 2.2
标准差: 1.16619037896906
方差: 1.3599999999999999
最小值最大值: 1 4
最小值和最大值的索引: 2 0
所有元素的累计和与累计积: [ 4  7  8 10 11] [ 4 12 12 24 24]
找出数组中的唯一值并返回已排序的结果: [1 2 3 4]
把一个数组重复若干次: [4 3 1 2 1 4 3 1 2 1]
按照轴向重复一个数组若干次: [4 4 3 3 1 1 2 2 1 1]
排序: [1 1 2 3 4]
